### ISSUE TITLE
More Items

### ISSUE THREAD

**Issue by benlpvt** [BurlingtonCodeAcademy/zorkington-bapzen#11]
More rooms and more stories, e.g.
when you unlock the door to the foyer it stays unlocked

read paper or read seven days

go up or go upstairs

Bob speaks gibberish until you get him a cup of tea from Muddy's

then you can attend lecture or sit down or some other command to attend class
After class you are hungry (status) which makes your stomach growl before every prompt

buying and eating a slice of pizza at Mr. Mike's removes the status
xyzzy

Please write stories for each of these features before implementing them.

**Comment by benlpvt** [comment]
- [X ] unlock the foyer and it stays unlocked,

**Comment by bapzen** [comment]
Bob speaks gibberish until you get him a cup of tea from Muddy's

**Comment by benlpvt** [comment]
@mxcostes 
These three are already done:

- when you unlock the door to the foyer it stays unlocked
- read paper or read seven days
- go up or go upstairs

**Comment by mxcostes** [comment]
bob requiring tea
getting tea from muddys
give tea
bob answers

**Comment by benlpvt** [comment]
All set. All of these functions are now in the master branch. Game is running well.
